user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  remember: 1
  per_page: 10

user_helper:
  size: 80
views:
  users:
    _user:
      size: 50
    show_follow:
      size: 30
sessions:
  remember: "1"
micropost:
  size_user: 50
  picture_size: 5
model:
  user:
    time: 2
